buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath("io.freefair.lombok:io.freefair.lombok.gradle.plugin:8.12.1")
    }
}

allprojects {
    apply plugin: "io.freefair.lombok"

    version = '0.1'
    ext {
        appName = "BomberTurtle"
        gdxVersion = '1.12.1'
        junitVersion = '5.7.1'
    }

    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        maven { url = "https://oss.sonatype.org/content/repositories/releases/" }
    }
}

project(":desktop") {
    apply plugin: "java-library"

    dependencies {
        implementation project(":core")
        api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
        api "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
        api "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"
    }
}

project(":core") {
    apply plugin: "java-library"

    dependencies {
        api "com.badlogicgames.gdx:gdx:$gdxVersion"
        api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
        implementation "org.junit.jupiter:junit-jupiter:$junitVersion"
        runtimeOnly "org.junit.platform:junit-platform-launcher"
    }

}
